theme: jekyll-theme-cayman
title: Will’s Inventory
repotitle: Will’s Inventory
author: Will/WHASonYT
url: https://willm.ga
favicon: https://cdn.discordapp.com/attachments/385252858028621824/403722101661368324/UKTV_channel_W_logo.png
